title: SustainaTrip
email: contato@sustainatrip.com.br
description: >
  Blog sobre turismo sustentável, viagens, cultura e experiências.

url: "https://blog.sustainatrip.com.br"
baseurl: ""

lang: pt-BR
timezone: America/Sao_Paulo
avatar: /images/logo_dark.png

markdown: kramdown
highlighter: rouge

permalink: /blog/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
