title: SustainaTrip
email: contato@sustainatrip.com
description: >
  Blog sobre turismo sustentável, viagens, cultura e experiências.

url: "https://sustainatrip.com.br"
baseurl: ""

lang: pt-BR
timezone: America/Sao_Paulo

markdown: kramdown
highlighter: rouge

permalink: /blog/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

collections: {}

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
